version: "3.9"
services:
  python:
    build:
      dockerfile: Dockerfile
    container_name: python
    tty: true
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - postgresql
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresql:5432/${POSTGRES_DB}?sslmode=disable

  postgresql:
    container_name: postgresql
    build: ./postgresql
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - ./postgresql/init:/docker-entrypoint-initdb.d
    ports:
      - 15432:5432
